# Generated by Django 5.1.1 on 2024-10-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_rename_cnjp_restaurantes_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantes',
            old_name='nome',
            new_name='razao_social',
        ),
    ]
