# Generated by Django 5.1.1 on 2024-10-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntarios',
            old_name='id_restaurante',
            new_name='id_voluntario',
        ),
    ]
