# Generated by Django 5.1.1 on 2024-10-01 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanha', '0001_initial'),
        ('voluntarios', '0002_rename_id_restaurante_voluntarios_id_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluida', 'Concluída')], default='Pendente', max_length=20)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='campanha.campanha')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='voluntarios.voluntarios')),
            ],
        ),
    ]
